# Generated by Django 2.2.14 on 2020-09-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description lorem ipsum bla blabla bla'),
            preserve_default=False,
        ),
    ]
