# Generated by Django 2.2.14 on 2020-09-20 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200919_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 6, 55, 9, 944921, tzinfo=utc)),
        ),
    ]
